### PR TITLE
Utilize BodySet as a trait object instead of param

### PR DESCRIPTION
**Pull request by distransient**
This commit prevents BodySet from polluting as a type parameter into all the core types required for physics stepping. Thanks to this, problems involved in dealing with these types in Specs usage are alleviated. However, this commit also removes the associated type of Body and always assumes dynamic dispatch on the Body type. This is an evolution of #226 that loosens future restrictions mentioned in that thread.

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thank you for this PR! Since this is a significant change, I won't have time to review this in depth before November.

After a quick look, my main concern is the performance impact since this adds virtual function calls. We should add some benchmarks (in a separate PR that would be merged before this one) to check that.

**Comment by distransient** [comment]
👍 no problem. I do want to point out that assuming `dyn Body` for `BodySet` is not necessary for this PR, but heavily simplifies it, since all the places that would've previously been polluted with `BodySet` parameters would've then also been polluted with `Body<N>` parameters, and the trickiness of `?Sized`.

**Comment by sebcrozet** [comment]
I did not notice any performance regression with this change (by comparing the step times on our examples, before and after this change).

I took the liberty of pushing a couple of minor changes (fixing the `DefaultMechanicalWorld` alias and running `cargo fmt`).
Waiting for the CI to succeed in order to merge this.

**Comment by sebcrozet** [comment]
All green. Thanks @distransient!

**Comment by eldyer** [comment]
@distransient Thanks a lot for this change, this works great and made my integration with specs much easier!

**Comment by distransient** [comment]
I've been caught up with school last two days, but glad my PR could help! ^^

**Pull request merged**
