### PR TITLE
Add methods to disable rotations on RigidBody

### LINKED ISSUE #145: Add a method to disable rotations on RigidBody.
The common way of doing this is to set its angular inertia to zero. However, users unfamiliar with inertia may not think of it. Thus we should add a method that does that.

### PR DESCRIPTION
**Pull request by fabienjuif**
Fixes #145 

Feel free to discuss the code, I am pretty new to Rust, and not good at Math :)

Not that I tested this with: https://github.com/fabienjuif/server-physic/pull/1
This part: https://github.com/fabienjuif/server-physic/pull/1/files#diff-639fbc4ef05b315af92b4d836c31b023R63

### CODE REVIEW

**Comment by fabienjuif** [comment]
I can squash commit before you merge if you want to.

**Comment by fabienjuif** [comment]
Hi @sebcrozet I see you did some commits on the repository.
Do you have time to look at my PRs ? (this one and that one:  https://github.com/rustsim/nphysics/pull/166)

Event if this is a NOGO ;)

**Comment by sebcrozet** [comment]
Hi @fabienjuif! Thank you for your PR and I'm very sorry for the late answer here. It's been a rough couple of months for me and I also had a lot of work related to the incoming release of nphysics so several PR just slipped my mind. So thank you for pinging me here 👍 

Regarding this PR, what you did here is very good and would work. However, these is a more generic way of doing this so we can disable rotations and/or translations wrt. individual axises. I've already implemented it in my local clone (on the deformable branch) so I will unfortunately not merge this PR. Sorry for overwriting your work here, I should have taken a look earlier and discussed it with you.

The basic idea is to setup a mask that will cancel all force components that are being locked. You can see [that diff](https://github.com/rustsim/nphysics/commit/d0dd346a19504f38a6392c306421228bccc72e1c) I've pushed a minute ago.

**Comment by fabienjuif** [comment]
Don't worry, I took this PR to learn a bit about nphysics (and physics, and rust) :)

**Pull request closed without merging**
