### PR TITLE
Expose narrow-phase setter

### PR DESCRIPTION
**Pull request by Ralith**
When combined with https://github.com/rustsim/ncollide/pull/271, allows the use of custom shapes.

### CODE REVIEW

**Comment by Ralith** [comment]
CI failure looks spurious; seems like the wasm infra is broken.

**Comment by Ralith** [comment]
Is this blocked?

**Comment by sebcrozet** [comment]
@Ralith Sorry, I forgot about this PR somehow. We can't expose the collision world mutably because that would allow the user to do things (like removing a collision object) that would break the invariants of the `ColliderWorld`. In order to expose rustsim/ncollide#271 we need to add to `ColliderWorld` a method that is only for setting the narrow-phase instead of providing full mutable access.

**Comment by Ralith** [comment]
Thanks for taking a look! How's this?

**Comment by sebcrozet** [comment]
Thanks! Would you mind re-adding the `as_collider_world` and marking it as deprecated in favor to `as_collision_world`? That would avoid a breaking change.

**Comment by Ralith** [comment]
Good thought; done.

**Comment by sebcrozet** [comment]
Thanks!

**Pull request merged**
