### PR TITLE
Make `ColliderDesc` derive `Clone`.

### PR DESCRIPTION
**Pull request by ndarilek**
I'm not sure if this is a terrible idea, but this lets me do:

```
struct Body(Vec<ColliderDesc<f32>>);

        // Create my simple Player shape.
        let body_shape = ShapeHandle::new(Ball::new(radius));
        let mut collision_groups = CollisionGroups::new();
        collision_groups.set_membership(&[2]);
        let body_collider = ColliderDesc::new(body_shape)
            .set_collision_groups(collision_groups)
            .clone();
        let body = Body(vec![body_collider]);
```

Then I have a single place in my code that detects when a `Body` component is added, then iterates through the colliders I create and adds them. It probably isn't terribly helpful for more complex use cases, but for my simple case of wanting to model a physical environment and not caring a whole lot about the actual physics, it beats creating a separate struct identical to `ColliderDesc` just so I can copy over the values from something that isn't a reference.

I'm open to deriving `Clone` not being the best solution. Maybe an `.into_owned()` method that returns `self` rather than `&self` or something else. And maybe there's an easy workaround I'm just missing. I mainly wanted to see if this compiled, and when it did, I thought I'd save you a bit of work. :)

Thanks.

### CODE REVIEW

**Comment by Ralith** [comment]
`ColliderDesc::build` doesn't consume `self`, so why not just keep the original around?

**Comment by ndarilek** [comment]
Because I don't always have access to the world, which is a necessary 
argument for `build`. I could potentially do this in a way where I *did* 
have access to the world, but then my code is responsible for both 
creating colliders/bodies *and* adding/removing them from the world.


This way, I create the colliders separately, and there's a single system 
that detects that they're available and should be added, and later 
removed when the ECS drops them.

**Comment by Ralith** [comment]
If you need to stash multiple references for your ECS to process later, you can use an `Arc`.

**Comment by ndarilek** [comment]
So you're saying:


```

struct Body(Vec<Arc<&ColliderDesc<f32>>>);
```


This starts to lead me down lifetime rabbit holes. Can an Arc help with 
the situation where you have a reference, though? Doesn't the reference 
go away when the function ends, and if so, what then remains in the Arc?

**Comment by Ralith** [comment]
You'd want to do `Arc<ColliderDesc<f32>>`. Putting a reference inside an `Arc` doesn't usually make sense.

**Comment by ndarilek** [comment]
Right, that's what I thought. And while the API seems to let you reuse a 
`ColliderDesc` in contexts where a reference is fine, there seems to be 
no provision for storing them in one context, then creating/populating 
the world in another.


Unless I'm genuinely missing something obvious. Sorry, not trying to be 
difficult--the API surface of all these projects is big. But it isn't at 
all obvious to me how an `Arc` should get me any closer to a solution here.


Maybe the right answer here is to make `new` return `Self`, not `&Self`. 
I assumed there was a reason for the latter, which is why I didn't make 
that change.


Thanks.

**Comment by ndarilek** [comment]
Oh, I'm an idiot.

The issue was that I was trying to chain method calls. If I just create an instance and call methods on it, things work just fine.

Sorry for the noise.

**Pull request closed without merging**
