### PR TITLE
Fixes #231

### LINKED ISSUE #231: nphysics panics when calling mechanical_wolrd.step() on wasm
I get a crash when compiling to wasm.
I am using wasm-bindgen and I configured nphysics2d with:
```
nphysics2d = { version = "0.12.3", default-features = false, features = [ "dim2", "use-wasm-bindgen"] }
```
The code is:
```pub struct PhysicsSystem {
    mechanical_world: DefaultMechanicalWorld<f32>,
    geometrical_world: DefaultGeometricalWorld<f32>,
    bodies: DefaultBodySet<f32>,
    colliders: DefaultColliderSet<f32>,
    joint_constraints: DefaultJointConstraintSet<f32>,
    force_generators: DefaultForceGeneratorSet<f32>,
}

impl PhysicsSystem {
    pub fn new() -> Self {
        let mechanical_world = DefaultMechanicalWorld::new(Vector2::new(0.0, -9.8));
        let geometrical_world = DefaultGeometricalWorld::new();
        let bodies = DefaultBodySet::new();
        let colliders = DefaultColliderSet::new();
        let joint_constraints = DefaultJointConstraintSet::new();
        let force_generators = DefaultForceGeneratorSet::new();
        Self {
            mechanical_world,
            geometrical_world,
            bodies,
            colliders,
            joint_constraints,
            force_generators,
        }
    }
}

impl<'a> System<'a> for PhysicsSystem {
    //TODO: get entities with a collider and update them
    type SystemData = (WriteStorage<'a, Collider>, WriteStorage<'a, Position>);

    fn run(&mut self, (mut collider, mut position): Self::SystemData) {
        use specs::Join;
        for (collider, position) in (&mut collider, &mut position).join() {
            if let Some(body) = collider.body {
                let new_pos = self
                    .bodies
                    .rigid_body(body)
                    .expect("Handle has no rigid body")
                    .position();
                position.x = new_pos.translation.x as f64;
                position.y = new_pos.translation.y as f64;
            } else {
                let body = RigidBodyDesc::new()
                    .translation(Vector2::new(position.x as f32, position.y as f32))
                    .gravity_enabled(true)
                    .build();
                collider.body = Some(self.bodies.insert(body));
            }
        }

        self.mechanical_world.step(
            &mut self.geometrical_world,
            &mut self.bodies,
            &mut self.colliders,
            &mut self.joint_constraints,
            &mut self.force_generators,
        );
    }
}
```
The error I get is: 
```
Uncaught TypeError: Illegal invocation
    at __wbg_now_f3d4527395a8a996 (bootstrap.js:119)
    at nphysics2d::counters::timer::Timer::resume::h27fe1051861dc01d (:8080/wasm-function[1224]:0x74f43)
    at nphysics2d::world::mechanical_world::MechanicalWorld<N,Bodies,CollHandle>::solve_ccd::he4afeab0bb314309 (:8080/wasm-function[26]:0x5f47)
    at nphysics2d::world::mechanical_world::MechanicalWorld<N,Bodies,CollHandle>::step::ha4b6957d1b477d1a (:8080/wasm-function[82]:0x27dcc)
    at <survival_client::systems::physics::PhysicsSystem as shred::system::System>::run::h2bbdda6fbaa09e2a (:8080/wasm-function[189]:0x43089)
    at survival_client::init::{{closure}}::h1f42b653f442990f (:8080/wasm-function[584]:0x66700)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hdf257caf7c4913b5 (:8080/wasm-function[1200]:0x74c11)
    at __wbg_elem_binding0 (survival_client.js:31)
    at real (survival_client.js:376)
```

### PR DESCRIPTION
**Pull request by Duddino**

### CODE REVIEW

**Comment by Duddino** [comment]
Sorry the mess I made with the names

**Comment by Duddino** [comment]
If you want something cleaner I can remake the pull request

**Comment by Ralith** [comment]
You can rewrite the pull request in-place using `git rebase -i` and then force-pushing.

**Comment by Duddino** [comment]
I'm making a mess... this currently doesn't work

**Comment by Duddino** [comment]
Alright I managed to clean it all up! Now it should be easier to read

**Comment by sebcrozet** [comment]
Thanks!

**Pull request merged**
